# Site settings
title: Evan Koch - Web Developer
email: evankoch@gmail.com
linkedin: evankoch
description: > # this means to ignore newlines until "baseurl:"
  I am a recent graduate of the Ruby on Rails Engineering course at The Iron Yard Atlanta.
  My design experience with Ruby on Rails is concentrated from January 2015, to date,
  and it has given me the confidence to explore other web-development technologies and fundamentals.
  I'm pursuing my passion to be a creator, designer, developer.<br>Seeking a SE-1/junior
  web development position.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evankoch.com/" # the base hostname & protocol for your site
twitter_username: evankkoch
github_username:  evo21

# Build settings
markdown: kramdown

# 
#  
#  
#  
#  
# 
